import express from "express";
import { spawn } from "child_process";

const app = express();
const PORT = 8080;
const INTERSTELLAR_PORT = 8081;

const PASSWORD = process.env.CONTROL_PASSWORD || "change-me";

let interstellar = null;

app.use(express.urlencoded({ extended: true }));

function isRunning() {
  return interstellar && !interstellar.killed;
  }

  app.get("/", (req, res) => {
    if (isRunning()) {
        res.send(`
              <!DOCTYPE html>
                    <html>
                          <head>
                                  <meta http-equiv="refresh" content="0;url=/interstellar">
                                          <title>Interstellar</title>
                                                </head>
                                                      <body>
                                                              Loading Interstellar...
                                                                    </body>
                                                                          </html>
                                                                              `);
                                                                                  return;
                                                                                    }

                                                                                      res.send(`
                                                                                          <!DOCTYPE html>
                                                                                              <html>
                                                                                                  <head>
                                                                                                        <title>Interstellar Server</title>
                                                                                                              <style>
                                                                                                                      body {
                                                                                                                                font-family: Arial, sans-serif;
                                                                                                                                          background: #111;
                                                                                                                                                    color: white;
                                                                                                                                                              display: flex;
                                                                                                                                                                        justify-content: center;
                                                                                                                                                                                  align-items: center;
                                                                                                                                                                                            height: 100vh;
                                                                                                                                                                                                      margin: 0;
                                                                                                                                                                                                              }

                                                                                                                                                                                                                      .box {
                                                                                                                                                                                                                                background: #222;
                                                                                                                                                                                                                                          padding: 35px;
                                                                                                                                                                                                                                                    border-radius: 12px;
                                                                                                                                                                                                                                                              width: 320px;
                                                                                                                                                                                                                                                                        text-align: center;
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                        input {
                                                                                                                                                                                                                                                                                                  width: 90%;
                                                                                                                                                                                                                                                                                                            padding: 12px;
                                                                                                                                                                                                                                                                                                                      margin: 15px 0;
                                                                                                                                                                                                                                                                                                                                border-radius: 6px;
                                                                                                                                                                                                                                                                                                                                          border: none;
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                          button {
                                                                                                                                                                                                                                                                                                                                                                    padding: 12px 20px;
                                                                                                                                                                                                                                                                                                                                                                              border: none;
                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 6px;
                                                                                                                                                                                                                                                                                                                                                                                                  cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                                                                                    </head>

                                                                                                                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="box">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <h1>Interstellar</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Server is currently offline.</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <form method="POST" action="/start">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit">Start Server</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.post("/start", (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (req.body.password !== PASSWORD) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(401).send("Incorrect password.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!isRunning()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        interstellar = spawn("npm", ["start"], {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              env: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...process.env,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              PORT: INTERSTELLAR_PORT.toString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          stdio: "inherit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                shell: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        interstellar.on("exit", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              interstellar = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.send(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <!DOCTYPE html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <meta http-equiv="refresh" content="3;url=/interstellar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>Starting Interstellar...</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>You will be redirected automatically.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.get("/interstellar", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.redirect(`http://localhost:${INTERSTELLAR_PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`Control server running on http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });